# Generated by Django 5.1.3 on 2024-12-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contact_details',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
